services:
  - type: web
    name: excel-extractor
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true

